image: comp1531/basic:latest

stages:
  - automarking

before_script:
  - git config user.email "comp1531-marker@cse.unsw.edu.au"
  - git config user.name "comp1531-marker"
  - git merge remotes/origin/submission --allow-unrelated-histories -X ours -m "Automarking"
  - mv -nv automarking-lock package-lock.json
  - npm ci

automarking:
  stage: automarking
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - python3 automarking.py $CI_PROJECT_NAME
  only:
    - marking
  artifacts:
    paths:
      - mark.txt